/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigSchema {
  $schema?: string;
  features?: {
    regression?: {
      enabled?: boolean;
      mode?: "full" | "compact" | "html";
      failOn?: "info" | "warning" | "error";
      reporting?: {
        html?: {
          enabled?: boolean;
          outputPath?: string;
        };
      };
      ai?: {
        enabled?: boolean;
        provider?: "ollama";
        host?: string;
        model?: string;
        language?: string;
      };
      severity?: {
        "cross-boundary"?: "info" | "warning" | "error";
        "deep-internal"?: "info" | "warning" | "error";
        sibling?: "info" | "warning" | "error";
        internal?: "info" | "warning" | "error";
      };
      thresholds?: {
        internalDepth?: number;
        deepInternalResidualDepth?: number;
      };
      scopes?: {
        match: string;
        ignore?: boolean;
        severity?: {
          "cross-boundary"?: "info" | "warning" | "error";
          "deep-internal"?: "info" | "warning" | "error";
          sibling?: "info" | "warning" | "error";
          internal?: "info" | "warning" | "error";
        };
        thresholds?: {
          internalDepth?: number;
          deepInternalResidualDepth?: number;
        };
      }[];
      history?: {
        enabled?: boolean;
        sampleSize?: number;
        strategy?: "incremental" | "cumulative" | "both";
        mode?: "full" | "compact" | "html";
      };
    };
    scc?: {
      enabled?: boolean;
      mode?: "full" | "compact" | "html";
      failOn?: "info" | "warning" | "error";
      reporting?: {
        html?: {
          enabled?: boolean;
          outputPath?: string;
        };
      };
      severity?: "info" | "warning" | "error";
      maxSize?: number;
    };
  };
}
